import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

import type { FeishuConfig } from '../wizard/feishu-config.js';
import type { CLIConfig } from '../cli-provider/interface.js';

export interface FullConfig {
  feishu: FeishuConfig;
  cli: Record<string, CLIConfig>;
  session?: { max_sessions?: number; max_history?: number };
  streaming?: { update_interval?: number; min_chunk_size?: number; max_message_length?: number };
  project?: { storage_path?: string; max_projects?: number };
  security?: { allowed_project_root?: string; max_attachment_size?: number; max_prompt_length?: number };
  debug?: { log_level?: string; save_logs?: boolean; log_dir?: string };
}

export function writeConfigFile(config: FullConfig, filePath: string): void {
  const yaml = generateYAML(config);
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, yaml, 'utf-8');
}

function generateYAML(config: FullConfig): string {
  const lines: string[] = [];

  lines.push('# Feishu CLI Bridge Configuration');
  lines.push('# Generated by setup wizard');
  lines.push('');

  // Feishu
  lines.push('feishu:');
  lines.push(`  app_id: ${quote(config.feishu.appId)}`);
  lines.push(`  app_secret: ${quote(config.feishu.appSecret)}`);
  if (config.feishu.encryptKey) {
    lines.push(`  encrypt_key: ${quote(config.feishu.encryptKey)}`);
  }
  if (config.feishu.verificationToken) {
    lines.push(`  verification_token: ${quote(config.feishu.verificationToken)}`);
  }
  lines.push('');

  // CLI
  lines.push('cli:');
  for (const [name, c] of Object.entries(config.cli)) {
    lines.push(`  ${name}:`);
    lines.push(`    enabled: ${c.enabled}`);
    lines.push(`    command: ${quote(c.command as string)}`);
    lines.push(`    default_model: ${quote(c.default_model as string)}`);
    if (c.timeout !== undefined) {
      lines.push(`    timeout: ${c.timeout}`);
    }
    if (Array.isArray(c.models) && c.models.length > 0) {
      lines.push('    models:');
      for (const m of c.models) {
        lines.push(`      - ${quote(m)}`);
      }
    }
  }
  lines.push('');

  // Session
  lines.push('session:');
  lines.push(`  max_sessions: ${config.session?.max_sessions ?? 15}`);
  lines.push(`  max_history: ${config.session?.max_history ?? 20}`);
  lines.push('');

  // Streaming
  lines.push('streaming:');
  lines.push(`  update_interval: ${config.streaming?.update_interval ?? 0.3}`);
  lines.push(`  min_chunk_size: ${config.streaming?.min_chunk_size ?? 20}`);
  lines.push(`  max_message_length: ${config.streaming?.max_message_length ?? 8000}`);
  lines.push('');

  // Security
  lines.push('security:');
  lines.push(`  allowed_project_root: ${quote(config.security?.allowed_project_root ?? '/')}`);
  lines.push(`  max_attachment_size: ${config.security?.max_attachment_size ?? 50 * 1024 * 1024}`);
  lines.push(`  max_prompt_length: ${config.security?.max_prompt_length ?? 100_000}`);
  lines.push('');

  // Debug
  lines.push('debug:');
  lines.push(`  log_level: ${quote(config.debug?.log_level ?? 'info')}`);
  lines.push(`  save_logs: ${config.debug?.save_logs ?? true}`);
  if (config.debug?.log_dir) {
    lines.push(`  log_dir: ${quote(config.debug.log_dir)}`);
  }
  lines.push('');

  // Project
  lines.push('project:');
  lines.push(`  storage_path: ${quote(config.project?.storage_path ?? '')}`);
  lines.push(`  max_projects: ${config.project?.max_projects ?? 50}`);
  lines.push('');

  return lines.join('\n');
}

function quote(value: string): string {
  if (!value) return '""';
  if (/[:#{}[\],&*?\|\-<>=!%@`]/.test(value) || value.startsWith(' ') || value.endsWith(' ')) {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}
